In [52]:
from json import load
import pandas as pd
import requests
from datetime import datetime, timezone
import zoneinfo
import os
from dotenv import load_dotenv

load_dotenv()

True

In [53]:
# Generate OAuth Token
def get_oauth_token():
    url_token = os.getenv("URL_TOKEN_OAUTH")
    headers = {
        "Content-Type": "application/x-www-form-urlencoded",
        "Authorization": "Basic " + os.getenv("RTE_API_KEY")
    }
    try:
        response_token = requests.post(url_token, headers=headers)
        if response_token.status_code == 200:
            data = response_token.json()
            return data["access_token"]
        else:
            raise Exception(f"Token Error: {response_token.status_code}")
    except Exception as e:
        raise(e)

token = get_oauth_token()
print(token)

NKG1rWwwZlIIYc1SK0f1O19PIDBHjYlOUyJR7oVgboznLnvYJCPnhG

In [54]:
# get historical annual data
def get_historical_data(token, year):
    api_url = os.getenv("URL_API")

    headers = {
        "Authorization": "Bearer " + token
    }
    print(headers)

    """params = {
        "start_date": format_date(f'{year}-01-01'),
        "end_date": format_date(f'{year}-06-01')
    }"""
    #params = {'start_date': '2022-01-01T00:00:00Z', 'end_date': '2022-07-01T00:00:00Z'}
    params = {'start_date': '2022-06-30T00:00:00Z', 'end_date': '2023-01-01T00:00:00Z'}
    print(params)
    try:
        response = requests.get(api_url, headers=headers, params=params)
        print(response.url)
        if response.status_code == 200:
            data = response.json()
            print(data)
            print(len(data["consolidated_power_consumption"][0]['values']))
            return data
        else:
            data_error = response.json()
            raise Exception(f"API Error {response.status_code}  : {data_error['error']} + ' : ' + {data_error['error_description']}")

    except Exception as e:
        print(e)

def format_date(date: str, input_format="%Y-%m-%d", output_format="%Y-%m-%dT%H:%M:%S%z"):
    dt = datetime.strptime(date, "%Y-%m-%d")
    # Add hour and timezone Paris
    tz_paris = zoneinfo.ZoneInfo("Europe/Paris")
    dt_tz = dt.replace(hour=0, minute=0, second=0, tzinfo=tz_paris)
    return dt_tz.strftime("%Y-%m-%dT%H:%M:%S%z")

In [55]:
def get_historical_energy_consumption(token, year):
    api_url = os.getenv("URL_API_ENERGY_CONSUMPTION")

    headers = {
        "Authorization": "Bearer " + token
    }
    print(headers)

    """params = {
        "start_date": format_date(f'{year}-01-01'),
        "end_date": format_date(f'{year}-06-01')
    }"""
    #params = {'start_date': '2022-01-01T00:00:00Z', 'end_date': '2022-07-01T00:00:00Z'}
    params = {'start_date': '2010-01-01T00:00:00Z', 'end_date': '2011-01-01T00:00:00Z'}
    print(params)
    try:
        response = requests.get(api_url, headers=headers, params=params)
        print(response.url)
        if response.status_code == 200:
            data = response.json()
            print(data)
            print(len(data["consolidated_energy_consumption"][0]['values']))
            return data
        else:
            data_error = response.json()
            raise Exception(f"API Error {response.status_code}  : {data_error['error']} + ' : ' + {data_error['error_description']}")

    except Exception as e:
        print(e)

In [56]:
data = get_historical_energy_consumption(token, 2000)
data_values = data["consolidated_energy_consumption"][0]['values']
df = pd.DataFrame(data_values)
df.sort_values('end_date', inplace=True)
df.reset_index(inplace=True, drop=True)

{'Authorization': 'Bearer NKG1rWwwZlIIYc1SK0f1O19PIDBHjYlOUyJR7oVgboznLnvYJCPnhG'}
{'start_date': '2010-01-01T00:00:00Z', 'end_date': '2011-01-01T00:00:00Z'}
https://digital.iservices.rte-france.com/open_api/consolidated_consumption/v1/consolidated_energy_consumption?start_date=2010-01-01T00%3A00%3A00Z&end_date=2011-01-01T00%3A00%3A00Z

In [57]:
df.head()

                  start_date                   end_date    value status
0  2010-01-02T00:00:00+01:00  2010-01-03T00:00:00+01:00  1577704  FINAL
1  2010-01-03T00:00:00+01:00  2010-01-04T00:00:00+01:00  1617791  FINAL
2  2010-01-04T00:00:00+01:00  2010-01-05T00:00:00+01:00  1902952  FINAL
3  2010-01-05T00:00:00+01:00  2010-01-06T00:00:00+01:00  1972570  FINAL
4  2010-01-06T00:00:00+01:00  2010-01-07T00:00:00+01:00  1980309  FINAL

In [46]:
data = get_historical_data(token, 2010)
data_values = data["consolidated_power_consumption"][0]['values']
df = pd.DataFrame(data_values)
df.sort_values('end_date', inplace=True)
df.reset_index(inplace=True, drop=True)

{'Authorization': 'Bearer ByylN0c9s463Hm5Wyp98740sRQbAKh4c98vSCMXq1hTNeTq680fItI'}
{'start_date': '2022-06-30T00:00:00Z', 'end_date': '2023-01-01T00:00:00Z'}
https://digital.iservices.rte-france.com/open_api/consolidated_consumption/v1/consolidated_power_consumption?start_date=2022-06-30T00%3A00%3A00Z&end_date=2023-01-01T00%3A00%3A00Z

In [48]:
df.tail()

,start_date,end_date,value,updated_date,status
8827,2022-12-31T21:30:00+01:00,2022-12-31T22:00:00+01:00,45130,2023-10-23T17:38:54+02:00,FINAL
8828,2022-12-31T22:00:00+01:00,2022-12-31T22:30:00+01:00,45842,2023-10-23T17:38:54+02:00,FINAL
8829,2022-12-31T22:30:00+01:00,2022-12-31T23:00:00+01:00,47736,2023-10-23T17:38:54+02:00,FINAL
8830,2022-12-31T23:00:00+01:00,2022-12-31T23:30:00+01:00,47566,2023-10-23T17:38:54+02:00,FINAL
8831,2022-12-31T23:30:00+01:00,2023-01-01T00:00:00+01:00,47689,2023-10-23T17:38:54+02:00,FINAL

In [ ]:
data_values = data["consolidated_power_consumption"][0]['values']
df = pd.DataFrame(data_values)
df.sort_values('end_date', inplace=True)
df.reset_index(inplace=True, drop=True)

In [29]:
df.describe()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7248 entries, 0 to 7247
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   start_date    7248 non-null   object
 1   end_date      7248 non-null   object
 2   value         7248 non-null   int64
 3   updated_date  7248 non-null   object
 4   status        7248 non-null   object
dtypes: int64(1), object(4)
memory usage: 283.3+ KB

In [40]:
df.to_csv("./csv/2015_0106_consolidated_power_consumption.csv", index=False)