In [2]:
import pandas as pd

In [3]:
df_power = pd.read_csv('./csv/2010_power_consumption.csv')
df_power.head(10)

                  start_date                   end_date  value status
0  2010-01-01T00:00:00+01:00  2010-01-01T00:30:00+01:00  61437  FINAL
1  2010-01-01T00:30:00+01:00  2010-01-01T01:00:00+01:00  59663  FINAL
2  2010-01-01T01:00:00+01:00  2010-01-01T01:30:00+01:00  59839  FINAL
3  2010-01-01T01:30:00+01:00  2010-01-01T02:00:00+01:00  59634  FINAL
4  2010-01-01T02:00:00+01:00  2010-01-01T02:30:00+01:00  59361  FINAL
5  2010-01-01T02:30:00+01:00  2010-01-01T03:00:00+01:00  57401  FINAL
6  2010-01-01T03:00:00+01:00  2010-01-01T03:30:00+01:00  55736  FINAL
7  2010-01-01T03:30:00+01:00  2010-01-01T04:00:00+01:00  54155  FINAL
8  2010-01-01T04:00:00+01:00  2010-01-01T04:30:00+01:00  53067  FINAL
9  2010-01-01T04:30:00+01:00  2010-01-01T05:00:00+01:00  52303  FINAL

In [14]:
df_energy = pd.read_csv('./csv/2010_energy_consumption.csv')
df_energy['value2'] = round(df_energy['value'] / 1000)
df_energy.head(10)

,start_date,end_date,value,status,value2
0,2010-01-01T00:00:00+01:00,2010-01-02T00:00:00+01:00,1419043,FINAL,1419.0
1,2010-01-02T00:00:00+01:00,2010-01-03T00:00:00+01:00,1577704,FINAL,1578.0
2,2010-01-03T00:00:00+01:00,2010-01-04T00:00:00+01:00,1617791,FINAL,1618.0
3,2010-01-04T00:00:00+01:00,2010-01-05T00:00:00+01:00,1902952,FINAL,1903.0
4,2010-01-05T00:00:00+01:00,2010-01-06T00:00:00+01:00,1972570,FINAL,1973.0
5,2010-01-06T00:00:00+01:00,2010-01-07T00:00:00+01:00,1980309,FINAL,1980.0
6,2010-01-07T00:00:00+01:00,2010-01-08T00:00:00+01:00,1991017,FINAL,1991.0
7,2010-01-08T00:00:00+01:00,2010-01-09T00:00:00+01:00,2035951,FINAL,2036.0
8,2010-01-09T00:00:00+01:00,2010-01-10T00:00:00+01:00,1961497,FINAL,1961.0
9,2010-01-10T00:00:00+01:00,2010-01-11T00:00:00+01:00,1854320,FINAL,1854.0

In [6]:
df_power['start_date'] = pd.to_datetime(df_power['start_date'], utc=True).dt.tz_convert('Europe/Paris')
df_power['end_date'] = pd.to_datetime(df_power['end_date'], utc=True).dt.tz_convert('Europe/Paris')
df_power['day_of_year'] = df_power['start_date'].dt.dayofyear

In [12]:
df2 = df_power.groupby('day_of_year')['value'].sum().reset_index()
df2['value'] = round(df2['value'] / 2000)
df2.head(10)

   day_of_year   value
0            1  1418.0
1            2  1577.0
2            3  1616.0
3            4  1902.0
4            5  1972.0
5            6  1979.0
6            7  1990.0
7            8  2034.0
8            9  1960.0
9           10  1852.0