In [2]:
import pandas as pd
from dotenv import load_dotenv
import os
load_dotenv()

True

In [5]:
os.getenv('DATA_STORAGE')

'../../../data/csv/'

In [3]:
df_rte = pd.read_csv(os.getenv('DATA_STORAGE') + 'power_consumption_meteo_2000_2025_hourly.csv')
df_rte.head()

,start_date,end_date,value,mean,min,max,median,std,q1,q3
0,2000-01-01 00:00:00+01:00,2000-01-01 01:00:00+01:00,50094.0,5.110,-1.3,10.2,6.05,2.847932,2.775,6.650
1,2000-01-01 01:00:00+01:00,2000-01-01 02:00:00+01:00,49971.0,5.068,-1.7,10.1,5.95,2.887584,2.825,6.700
2,2000-01-01 02:00:00+01:00,2000-01-01 03:00:00+01:00,48666.5,5.066,-1.9,10.3,6.00,2.968516,2.675,6.900
3,2000-01-01 03:00:00+01:00,2000-01-01 04:00:00+01:00,45793.0,5.054,-2.2,10.5,6.00,3.054018,2.800,7.125
4,2000-01-01 04:00:00+01:00,2000-01-01 05:00:00+01:00,43498.5,5.074,-2.6,10.8,6.10,3.049577,3.200,7.175

In [4]:
df_rte['start_date'] = pd.to_datetime(df_rte['start_date'], utc=True).dt.tz_convert(None)
df_rte['end_date'] = pd.to_datetime(df_rte['end_date'], utc=True).dt.tz_convert(None)
df_rte.head()

,start_date,end_date,value,mean,min,max,median,std,q1,q3
0,1999-12-31 23:00:00,2000-01-01 00:00:00,50094.0,5.110,-1.3,10.2,6.05,2.847932,2.775,6.650
1,2000-01-01 00:00:00,2000-01-01 01:00:00,49971.0,5.068,-1.7,10.1,5.95,2.887584,2.825,6.700
2,2000-01-01 01:00:00,2000-01-01 02:00:00,48666.5,5.066,-1.9,10.3,6.00,2.968516,2.675,6.900
3,2000-01-01 02:00:00,2000-01-01 03:00:00,45793.0,5.054,-2.2,10.5,6.00,3.054018,2.800,7.125
4,2000-01-01 03:00:00,2000-01-01 04:00:00,43498.5,5.074,-2.6,10.8,6.10,3.049577,3.200,7.175

In [5]:
df_cut = df_rte[df_rte['start_date'] >= '2021-01-01']
df_cut.to_csv(os.getenv('DATA_STORAGE') + 'power_consumption_meteo_2021_2025_utc.csv', index=False)